export const keys = {
    'getInfoSystem': 'index/API/v1/init',
    'getProducts': 'index/API/v1/products',
    'deleteProduct': 'index/API/v1/products/delete',
    'registerProduct': 'index/API/v1/products/register',
    'updateProduct': 'index/API/v1/products/update',
    'modifyUnits': 'index/API/v1/products/modifyUnits',
    'getInfoUser': 'index/API/v1/getInfoUser',
    'loginUser': 'index/API/v1/login',
    'getUsers': 'index/API/v1/users',
    'getVentas': 'index/API/v1/ventas',
    'registerVenta': 'index/API/v1/ventas/register',
    'deleteVenta': 'index/API/v1/ventas/delete',
    'getGastos': 'index/API/v1/gastos',
    'registerGastos': 'index/API/v1/gastos/register',
    'updateGasto': 'index/API/v1/gastos/update',
    'deleteGasto': 'index/API/v1/gastos/delete',
    'registerUser': 'index/API/v1/users/register',
    'updateUser': 'index/API/v1/users/update',
    'deleteUser': 'index/API/v1/users/delete',
    'getDepositsBox': 'index/API/v1/box',
    'registerDeposits': 'index/API/v1/box'
}
