export const keys = {
    'getInfoSystem': 'https://farmazul-1.onrender.com/index/API/v1/init',
    'getProducts': 'https://farmazul-1.onrender.com/index/API/v1/products',
    'deleteProduct': 'https://farmazul-1.onrender.com/index/API/v1/products/delete',
    'registerProduct': 'https://farmazul-1.onrender.com/index/API/v1/products/register',
    'updateProduct': 'https://farmazul-1.onrender.com/index/API/v1/products/update',
    'descuentUnits': 'https://farmazul-1.onrender.com/index/API/v1/products/descuentUnits',
    'getInfoUser': 'https://farmazul-1.onrender.com/index/API/v1/getInfoUser',
    'loginUser': 'https://farmazul-1.onrender.com/index/API/v1/login',
    'getUsers': 'https://farmazul-1.onrender.com/index/API/v1/users',
    'getVentas': 'https://farmazul-1.onrender.com/index/API/v1/ventas',
    'registerVenta': 'https://farmazul-1.onrender.com/index/API/v1/ventas/register',
    'getGastos': 'https://farmazul-1.onrender.com/index/API/v1/gastos',
    'registerGastos': 'https://farmazul-1.onrender.com/index/API/v1/gastos/register',
    'updateGasto': 'https://farmazul-1.onrender.com/index/API/v1/gastos/update',
    'deleteGasto': 'https://farmazul-1.onrender.com/index/API/v1/gastos/delete',
    'registerUser': 'https://farmazul-1.onrender.com/index/API/v1/users/register',
    'updateUser': 'https://farmazul-1.onrender.com/index/API/v1/users/update',
    'deleteUser': 'https://farmazul-1.onrender.com/index/API/v1/users/delete',
    'getDepositsBox': 'https://farmazul-1.onrender.com/index/API/v1/box',
    'registerDeposits': 'https://farmazul-1.onrender.com/index/API/v1/box'
}
